from PIL import Image
import os

# ================= 配置区域 =================
# 输入图片文件名
INPUT_IMAGE = '7.png' 

# 输出的 C 语言头文件名
OUTPUT_FILE = 'image_array.h'

# 生成的数组变量名
VAR_NAME = 'myImageArray'

# 是否交换高低字节 (Swap Bytes)
# 如果生成的图片在屏幕上颜色反了(比如红变蓝)，或者花屏，请把这里改为 True
SWAP_BYTES = False  
# 注意：大多数 ESP32/Arduino 库（如 TFT_eSPI）读取数组时，
# 为了配合 SPI 的大端传输，通常需要在这里开启 Swap Bytes (即高低位互换)。
# 如果你发现颜色不对，改成 False 再试一次即可。
# ===========================================

def rgb888_to_rgb565(r, g, b):
    """将 RGB888 转换为 RGB565"""
    # 红色取高5位，绿色取高6位，蓝色取高5位
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)

def convert_image():
    if not os.path.exists(INPUT_IMAGE):
        print(f"错误: 找不到图片文件 {INPUT_IMAGE}")
        return

    img = Image.open(INPUT_IMAGE)
    # 强制转换为 RGB 模式（去除透明通道，防止报错）
    img = img.convert('RGB')
    
    width, height = img.size
    print(f"正在处理图片: {width}x{height}")
    
    pixels = list(img.getdata())
    total_pixels = len(pixels)
    
    print("正在转换颜色格式...")
    
    hex_array = []
    for r, g, b in pixels:
        val = rgb888_to_rgb565(r, g, b)
        
        if SWAP_BYTES:
            # 交换高低字节： 0xABCD -> 0xCDAB
            val = ((val & 0xFF) << 8) | ((val >> 8) & 0xFF)
            
        # 格式化为 0xXXXX 字符串
        hex_array.append(f"0x{val:04X}")

    # 生成 C 代码内容
    print(f"正在写入文件 {OUTPUT_FILE}...")
    
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write(f"// Generated by Python Script\n")
        f.write(f"// Image Size: {width} x {height}\n")
        f.write(f"#include <pgmspace.h>\n\n")
        
        # 写入数组定义
        # 注意: 0x{total_pixels:X} 是把总数变成16进制显示，比如 0x25800
        f.write(f"const unsigned short {VAR_NAME}[0x{total_pixels:X}] PROGMEM = {{\n")
        
        # 写入数据，每行写 16 个数据，方便阅读
        for i in range(0, len(hex_array), 16):
            chunk = hex_array[i:i+16]
            line = ", ".join(chunk)
            f.write(f"  {line},\n")
            
        f.write("};\n")

    print("完成！")
    print(f"请打开 {OUTPUT_FILE} 查看结果。")
    print(f"数组占用空间: {total_pixels * 2 / 1024:.2f} KB")

if __name__ == '__main__':
    convert_image()